[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp3-*"
archs = "auto64"
skip = "*-win32 *-musllinux_i686 *-manylinux_i686 cp36-*"
test-command = "python -c \"from mqt import bench\""
environment = { DEPLOY = "ON" }
build-verbosity = 3

[tool.cibuildwheel.linux]

[tool.cibuildwheel.macos]
archs = "x86_64"
environment = { MACOSX_DEPLOYMENT_TARGET = "10.15", DEPLOY = "ON" }

[tool.cibuildwheel.windows]