[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.

[tool.cibuildwheel]
build = "cp38*"
skip = "cp38-*"
build-verbosity = 3