[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.

[tool.cibuildwheel]
build = "cp38*"
skip = "cp38-*"
test-command = "python -c \"from mqt import bench\""
environment = { DEPLOY = "ON" }
build-verbosity = 3