name: Deploy to PyPI

on:
  release:
    types: [ published ]
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_m1_wheels:
    name:    Build wheels for Apple Silicon
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build wheels
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name:    Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v3
        name: Install Python
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -q build
      - name: Build sdist
        run:  python -m build --sdist
      - name: Test sdist
        run:  pip install --verbose dist/*.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  test_bindings:
    name:    Test Python bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'
      - name: Install package
        run:  pip install .
      - name: Test package
        run: cd test/python && coverage run -m pytest

  upload_pypi:
    needs: [ build_wheels, build_m1_wheels, build_sdist, test_bindings ]
    runs-on: ubuntu-latest
    if:      github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TEST }}
          repository_url: https://test.pypi.org/legacy/