name: Pre-generated zip with all benchmarks

on: [push, pull_request]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: benchviewer/static/files/qasm_output/ benchviewer/static/files/algo_level.txt
          dest: benchviewer/static/files/MQTBench_all.zip