name: Pre-generate zip with all benchmarks

on: [push, pull_request]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Creating zip file
      run:  zip -rj ./benchviewer/static/files/test.zip ./benchviewer/static/files/qasm_output/ ./benchviewer/static/files/algo_level.txt
