name: Lint

on: [push, pull_request]

jobs:
  Black:
    runs-on: ubuntu-latest
    steps:
      - uses: snow-actions/sparse-checkout@v1.1.0
        with:
          patterns: "mqt"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Black
        uses: psf/black@stable
